site_name: Ecommerce API
site_description: Documentação da API de e-commerce
site_author: Equipe de Desenvolvimento

theme:
  name: material
  language: pt-BR
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Início: index.md
  - Guia de Uso:
    - Autenticação: guia/autenticacao.md
    - Produtos: guia/produtos.md
    - Pedidos: guia/pedidos.md
    - Usuários: guia/usuarios.md
  # - API Reference:
  #   - Autenticação: api/autenticacao.md
  #   - Produtos: api/produtos.md
  #   - Pedidos: api/pedidos.md
  #   - Usuários: api/usuarios.md
  - Desenvolvimento:
    - Arquitetura: desenvolvimento/arquitetura.md
